---
- hosts: all
  sudo: yes

  tasks:
  - name: apt update
    apt: update_cache=yes
  - name: upgrade all packages
    apt: upgrade=dist
  - name: install basic package
    apt: pkg={{item}}
    with_items:
      - screen
      - language-pack-ja
      - postfix
      - mailutils
      - git
  - name: copy screen.rc
    copy: src=files/home/vagrant/.screenrc dest=/home/vagrant/.screenrc owner=vagrant mode=0644
    sudo: no

  - include: apache.yml
  - include: db.yml
  - include: drupal.yml

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
